export interface ProductType {
    id: number,
    title: string,
    description: string,
    category: string,
    price: number,
    discountPercentage : number,
    rating: number,
    stock: number,
    tags: Array<string>,
    brand ?: string,
    sku: string,
    weight: number,
    dimensions: {[key: string] : number},
    warrantyInformation: string,
    shippingInformation: string,
    availabilityStatus: string,
    reviews: Array<{[key: string]: string|number}>,
    returnPolicy: string,
    minimumOrderQuantity: number,
    meta: {[key:string]: string} ,
    images: Array<string>,
    thumbnail: string
}